# Generated by Django 5.0.9 on 2024-10-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_subcategory_category'),
        ('product', '0005_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='product',
            field=models.ManyToManyField(related_name='product', to='product.product'),
        ),
    ]
