# Generated by Django 5.0.9 on 2024-10-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_subcategory_product'),
        ('product', '0005_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='product', to='product.product'),
        ),
    ]
