# Generated by Django 5.0.9 on 2024-10-18 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_imagefieldmodel_remove_product_img1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefieldmodel',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='imagefieldmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='imagefieldmodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product'),
        ),
    ]
