# Generated by Django 5.0.9 on 2024-10-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_imagefieldmodel_images_remove_product_images_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageFieldModel',
            new_name='AddImages',
        ),
    ]
